name: toubkal
description: This is my personal OS image.

base-image: ghcr.io/wayblueorg/hyprland
image-version: latest 

modules:
  - from-file: common/00-files.yml
  - from-file: common/01-packages.yml
  - from-file: common/02-flatpaks.yml
  # - from-file: common/03-cleanup.yml
  - from-file: common/04-signing.yml
